spring:
  application:
    name: zipkin-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 7777
eureka:
  client:
    # fetch-registry: true
    # register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8777/eureka/"
