spring:
  application:
    name: limit-service
  cloud:
    config:
      uri:
        - http://localhost:8888
      profile: dev
  config:
    import:
      - configserver:http://localhost:8888
server:
  port: 8080